export const ADMIN_NAV = [
  { icon: "📊", label: "Overview",       href: "/admin" },
  { icon: "🎒", label: "Students",       href: "/admin/students" },
  { icon: "🧑‍🤝‍🧑", label: "Guardians",     href: "/admin/guardians" },
  { icon: "👨‍👩‍👧", label: "Families",       href: "/admin/families" },
  { icon: "🎓", label: "Course Groups",  href: "/admin/course-groups" },
  { icon: "💳", label: "Fee Management", href: "/admin/fees" },
  { icon: "📑", label: "Fee Particulars",  href: "/admin/fee-particulars" },
  { icon: "📊", label: "Fee Billing Setup", href: "/admin/fee-billing" },
  { icon: "💼", label: "Other Fees",       href: "/admin/other-fees" },
  { icon: "🏦", label: "Finance Accounts", href: "/admin/finance-accounts" },
  { icon: "💸", label: "Finance Payments", href: "/admin/finance-payments" },
  { icon: "📊", label: "Finance Reports",  href: "/admin/finance-reports" },
  { icon: "📈", label: "Fee Reports",      href: "/admin/fee-reports" },
  { icon: "🏷️", label: "Sibling Discount", href: "/admin/discount" },
  { icon: "👩‍🏫", label: "Staff",         href: "/admin/staff" },
  { icon: "🧰", label: "HR Settings",     href: "/admin/hr-settings" },
  { icon: "🧑‍💼", label: "Employees",       href: "/admin/employees" },
  { icon: "💼", label: "Payroll",        href: "/admin/payroll" },
  { icon: "📡", label: "Attendance",     href: "/admin/attendance" },
  { icon: "🏦", label: "Canteen Wallet", href: "/admin/canteen" },
  { icon: "🍱", label: "Canteen",        href: "/admin/canteen-module" },
  { icon: "🏫", label: "Classes & Subjects", href: "/admin/classes" },
  { icon: "📅", label: "Academic Calendar", href: "/admin/calendar" },
  { icon: "🕘", label: "Timetable",         href: "/admin/timetable" },
  { icon: "💻", label: "Online Learning",   href: "/admin/online-learning" },
  { icon: "📋", label: "Assessments",     href: "/admin/assessments" },
  { icon: "📐", label: "Grading & Remarks", href: "/admin/grading" },
  { icon: "💗", label: "Student Interests", href: "/admin/interests" },
  { icon: "📄", label: "Reports & Remarks", href: "/admin/reports" },
  { icon: "📢", label: "Announcements",   href: "/admin/announcements" },
  { icon: "📨", label: "Messaging Service", href: "/admin/messaging" },
  { icon: "📸", label: "School Feed",     href: "/admin/feed" },
  { icon: "🔑", label: "Accounts",        href: "/admin/accounts" },
  { icon: "❓", label: "Question Bank",   href: "/admin/questions" },
  { icon: "📥", label: "Data Import",     href: "/admin/import" },
  { icon: "📊", label: "Smart Reports",   href: "/admin/smart-reports" },
  { icon: "📤", label: "Data Uploads",    href: "/admin/data-uploads" },
  { icon: "📬", label: "Enquiries",       href: "/admin/enquiries" },
  { icon: "⚙️", label: "School Settings", href: "/admin/settings" },
];
