export const ADMIN_NAV = [
  { icon: "📊", label: "Overview",       href: "/admin" },
  { icon: "🎒", label: "Students",       href: "/admin/students" },
  { icon: "👨‍👩‍👧", label: "Families",       href: "/admin/families" },
  { icon: "💳", label: "Fee Management", href: "/admin/fees" },
  { icon: "🏷️", label: "Sibling Discount", href: "/admin/discount" },
  { icon: "👩‍🏫", label: "Staff",         href: "/admin/staff" },
  { icon: "💼", label: "Payroll",        href: "/admin/payroll" },
  { icon: "📡", label: "Attendance",     href: "/admin/attendance" },
  { icon: "🏦", label: "Canteen Wallet", href: "/admin/canteen" },
  { icon: "🏫", label: "Classes & Subjects", href: "/admin/classes" },
  { icon: "📅", label: "Academic Calendar", href: "/admin/calendar" },
  { icon: "📋", label: "Assessments",     href: "/admin/assessments" },
  { icon: "📄", label: "Reports & Remarks", href: "/admin/reports" },
  { icon: "📢", label: "Announcements",   href: "/admin/announcements" },
  { icon: "📸", label: "School Feed",     href: "/admin/feed" },
  { icon: "🔑", label: "Accounts",        href: "/admin/accounts" },
  { icon: "❓", label: "Question Bank",   href: "/admin/questions" },
  { icon: "📥", label: "Data Import",     href: "/admin/import" },
  { icon: "⚙️", label: "School Settings", href: "/admin/settings" },
];
